#!/usr/bin/env fish

touch $argv[2]
curl --connect-timeout 5 -s https://github.com/users/$argv[1]/contributions ^/dev/null | python -c 'import json; print(json.loads(raw_input())[-1][1])' > $argv[2].tmp
if [ $status -eq 0 ]
    mv $argv[2].tmp $argv[2]
else
    rm $argv[2].tmp
end
